spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpashop # MVCC=TRUE
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create            # create: application 실행 시 모든 엔티티를 지우고 다시 생성
    properties:
      hibernate:
        #        show_sql: true                  # sout 으로 로그 찍기
        format_sql: true
        default_batch_fetch_size: 100       # 컬렉션/프록시 객체를 설정한 size 만큼 IN 쿼리로 조회

logging:
  level:
    org.hibernate.SQL: debug            # log
    org.hibernate.type: trace           # query log 찍을 때 data parameter type 확인
